# Generated by Django 6.0.2 on 2026-05-25 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tankgauge", "0004_store_location_storetankmapping_tank_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Standardized name (e.g., Regular, Premium, Diesel).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "color_name",
                    models.CharField(
                        blank=True,
                        help_text="Visual identifier name.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        help_text="RGB Hex color (e.g., #8da35d).",
                        max_length=7,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuel Type",
                "verbose_name_plural": "Fuel Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_start",
                    models.DateTimeField(help_text="Duty log trigger time."),
                ),
                (
                    "shift_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Mission complete sign-off time.",
                        null=True,
                    ),
                ),
                (
                    "start_miles",
                    models.IntegerField(
                        blank=True,
                        help_text="Starting vehicle odometer reading.",
                        null=True,
                    ),
                ),
                (
                    "end_miles",
                    models.IntegerField(
                        blank=True,
                        help_text="Ending vehicle odometer reading.",
                        null=True,
                    ),
                ),
                (
                    "total_stops",
                    models.IntegerField(
                        default=0, help_text="Count of individual stop events."
                    ),
                ),
                (
                    "hours_on_duty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total duty hours logged.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="True if Jocko 'Mission Complete' protocol executed.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="General shift debrief observations.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "ordering": ["-shift_start"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "po_number",
                    models.IntegerField(
                        help_text="Primary PO identifier from commercial invoice."
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        help_text="Associated shift mission.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="missionlog.mission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "ordering": ["po_number"],
            },
        ),
        migrations.CreateModel(
            name="LoadDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_at_store",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pump retail price at store.",
                        max_digits=6,
                    ),
                ),
                (
                    "gross_gal",
                    models.IntegerField(help_text="Gross volume (gallons) from BOL."),
                ),
                (
                    "net_gal",
                    models.IntegerField(
                        help_text="Net volume (gallons) from BOL adjusted for temperature."
                    ),
                ),
                (
                    "temp",
                    models.FloatField(
                        help_text="Fuel temperature (Fahrenheit) logged on BOL."
                    ),
                ),
                (
                    "grav",
                    models.FloatField(
                        help_text="Specific gravity (GRAV) logged on BOL."
                    ),
                ),
                (
                    "start_inches",
                    models.FloatField(
                        help_text="Opening physical stick measurement (inches)."
                    ),
                ),
                (
                    "start_gallons",
                    models.FloatField(help_text="Opening volume (gallons)."),
                ),
                (
                    "end_inches",
                    models.FloatField(
                        help_text="Closing physical stick measurement (inches)."
                    ),
                ),
                (
                    "end_gallons",
                    models.FloatField(help_text="Closing volume (gallons)."),
                ),
                (
                    "fuel_type",
                    models.ForeignKey(
                        help_text="Associated standardized fuel classification.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="missionlog.fueltype",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        help_text="Physical Store Location anchor.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="tankgauge.store",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        help_text="Parent Purchase Order.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loads",
                        to="missionlog.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Load Delivery",
                "verbose_name_plural": "Load Deliveries",
            },
        ),
        migrations.CreateModel(
            name="TruckFuelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gallons",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Truck fuel gallons pumped.",
                        max_digits=10,
                    ),
                ),
                (
                    "price_per_gallon",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pump cost per gallon.",
                        max_digits=10,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="System logged timestamp."
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        help_text="Parent shift mission.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="missionlog.mission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Truck Fuel Log",
                "verbose_name_plural": "Truck Fuel Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
