# Generated by Django 6.0.2 on 2026-05-17 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("miles_started", models.IntegerField(default=0)),
                ("miles_ended", models.IntegerField(default=0)),
                (
                    "truck_fuel_gallons",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "truck_fuel_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "purchase_orders_json",
                    models.JSONField(
                        default=list, help_text="List of PO numbers for the day"
                    ),
                ),
                (
                    "stores_visited_json",
                    models.JSONField(
                        default=list, help_text="List of Store IDs visited"
                    ),
                ),
                (
                    "fuel_delivered_gallons",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "ordering": ["-date"],
            },
        ),
    ]
