# Generated by Django 6.0.2 on 2026-05-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missionlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loaddelivery",
            name="end_gallons",
            field=models.FloatField(
                blank=True, help_text="Closing volume (gallons).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loaddelivery",
            name="end_inches",
            field=models.FloatField(
                blank=True,
                help_text="Closing physical stick measurement (inches).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loaddelivery",
            name="grav",
            field=models.FloatField(
                blank=True,
                help_text="Specific gravity (GRAV) logged on BOL.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loaddelivery",
            name="gross_gal",
            field=models.IntegerField(
                blank=True, help_text="Gross volume (gallons) from BOL.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loaddelivery",
            name="net_gal",
            field=models.IntegerField(
                blank=True,
                help_text="Net volume (gallons) from BOL adjusted for temperature.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loaddelivery",
            name="price_at_store",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pump retail price at store.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loaddelivery",
            name="start_gallons",
            field=models.FloatField(
                blank=True, help_text="Opening volume (gallons).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loaddelivery",
            name="start_inches",
            field=models.FloatField(
                blank=True,
                help_text="Opening physical stick measurement (inches).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loaddelivery",
            name="temp",
            field=models.FloatField(
                blank=True,
                help_text="Fuel temperature (Fahrenheit) logged on BOL.",
                null=True,
            ),
        ),
    ]
