# Generated by Django 6.0.2 on 2026-05-25 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missionlog", "0002_alter_loaddelivery_end_gallons_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="purchaseorder",
        #     name="mission",
        # ),
        # migrations.CreateModel(
        #     name="OrderNumber",
        #     fields=[
        #         (
        #             "id",
        #             models.BigAutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name="ID",
        #             ),
        #         ),
        #         (
        #             "order_number",
        #             models.CharField(
        #                 help_text="Overarching Job/Order ID.", max_length=100
        #             ),
        #         ),
        #         (
        #             "mission",
        #             models.ForeignKey(
        #                 help_text="Associated shift mission.",
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 related_name="order_numbers",
        #                 to="missionlog.mission",
        #             ),
        #         ),
        #     ],
        #     options={
        #         "verbose_name": "Order Number",
        #         "verbose_name_plural": "Order Numbers",
        #     },
        # ),
        migrations.AddField(
            model_name="purchaseorder",
            name="order_parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent overarching order.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="missionlog.ordernumber",
            ),
        ),
    ]
