# Generated by Django 6.0.2 on 2026-05-26 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missionlog", "0003_remove_purchaseorder_mission_ordernumber_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="purchaseorder",
            unique_together={("order_parent", "po_number")},
        ),
        migrations.CreateModel(
            name="OrderNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="Overarching Job/Order ID.", max_length=100
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        help_text="Associated shift mission.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_numbers",
                        to="missionlog.mission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Number",
                "verbose_name_plural": "Order Numbers",
                "unique_together": {("mission", "order_number")},
            },
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="mission",
        ),
    ]
