# Generated by Django 6.0.2 on 2026-05-26 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missionlog", "0003_remove_purchaseorder_mission_ordernumber_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="purchaseorder",
            unique_together={("order_parent", "po_number")},
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="mission",
        ),
    ]
