# Generated by Django 6.0.2 on 2026-05-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missionlog", "0004_all_fixes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ordernumber",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorder",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="ordernumber",
            name="order_number",
            field=models.CharField(
                help_text="Overarching Job/Order ID.", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.IntegerField(
                help_text="Primary PO identifier from commercial invoice.", unique=True
            ),
        ),
    ]
