# Generated by Django 6.0.2 on 2026-06-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missionlog", "0005_global_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="hours_on_duty_not_driving",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total on-duty hours where the truck was not being driven.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
