# Generated by Django 6.0.2 on 2026-07-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missionlog", "0006_mission_hours_on_duty_not_driving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truckfuellog",
            name="gallons",
            field=models.DecimalField(
                decimal_places=3, help_text="Truck fuel gallons pumped.", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="truckfuellog",
            name="price_per_gallon",
            field=models.DecimalField(
                decimal_places=3, help_text="Pump cost per gallon.", max_digits=10
            ),
        ),
    ]
