# Generated by Django 6.0.2 on 2026-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missionlog", "0007_alter_truckfuellog_gallons_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fueltype",
            name="abbreviation",
            field=models.CharField(
                blank=True,
                help_text="Short code for DMS tags and filenames (e.g., RUL, DSL, PUL).",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
