# Generated by Django 6.0.2 on 2026-07-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missionlog", "0008_fueltype_abbreviation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="entry_type",
            field=models.CharField(
                blank=True,
                choices=[("basic", "Basic"), ("advanced", "Advanced")],
                help_text="Entry workflow used at mission creation. NULL indicates legacy mission.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="total_gallons",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total gallons delivered. Auto-calculated from LoadDelivery in advanced mode, manually entered in basic mode.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
