# Generated by Django 6.0.2 on 2026-08-03 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missionlog", "0009_mission_entry_type_mission_total_gallons"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionReportEmailAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_range",
                    models.CharField(
                        choices=[
                            ("week", "Week"),
                            ("month", "Month"),
                            ("quarter", "Quarter"),
                            ("year", "Year"),
                        ],
                        max_length=16,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("exception_type", models.CharField(blank=True, max_length=128)),
                ("generation_duration_ms", models.IntegerField(blank=True, null=True)),
                ("render_duration_ms", models.IntegerField(blank=True, null=True)),
                ("smtp_duration_ms", models.IntegerField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_report_email_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "requested_at"],
                        name="missionlog__user_id_bc3f3b_idx",
                    ),
                    models.Index(
                        fields=["report_range", "status"],
                        name="missionlog__report__040b67_idx",
                    ),
                ],
            },
        ),
    ]
