# Generated by Django 6.0.2 on 2026-06-08 12:28

import django.db.models.deletion
import dms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name", max_length=100, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug for API URLs", max_length=100, unique=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Is this category active?"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Order in lists (lower numbers first)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dms.models.generate_ulid,
                        editable=False,
                        help_text="Unique ULID identifier",
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="User-facing document name", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional document description", null=True
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original uploaded filename", max_length=255
                    ),
                ),
                (
                    "stored_filename",
                    models.CharField(
                        help_text="Filename stored in filesystem (ULID + ext)",
                        max_length=255,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Relative storage file path", max_length=500
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="MIME type verified via magic bytes", max_length=100
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "sha256",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 checksum for duplicate detection",
                        max_length=64,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when document was uploaded",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                            ("SUPERSEDED", "Superseded"),
                            ("DRAFT", "Draft"),
                        ],
                        default="ACTIVE",
                        help_text="Document lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version increment number"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Cumulative download count"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        help_text="Linked object primary key identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Controlled vocabulary category classification",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="dms.category",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked model content type (e.g. siteintel.Location)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the document",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dms.models.generate_ulid,
                        editable=False,
                        help_text="Unique ULID identifier",
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Collection package name", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Collection details", null=True
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Visible to standard users?"
                    ),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        help_text="Documents in this collection",
                        related_name="collections",
                        to="dms.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemporaryUpload",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dms.models.generate_ulid,
                        editable=False,
                        help_text="Unique ULID identifier",
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded temporary file location", upload_to="temp/"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Expiry timestamp after which file is purged"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        help_text="SHA256 checksum of raw file", max_length=64
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who performed raw upload",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Temporary Upload",
                "verbose_name_plural": "Temporary Uploads",
                "ordering": ["expires_at"],
            },
        ),
    ]
