# Generated by Django 6.0.2 on 2026-06-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when document was last updated"
            ),
        ),
    ]
