# Generated by Django 6.0.2 on 2026-06-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0002_document_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaryupload",
            name="original_filename",
            field=models.CharField(
                default="", help_text="Original uploaded filename", max_length=255
            ),
        ),
    ]
