# Generated by Django 6.0.2 on 2026-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0003_temporaryupload_original_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tag name", max_length=50, unique=True),
                ),
                ("slug", models.SlugField(help_text="Tag slug", unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Is this document visible to standard users?"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Flexible search and organization tags",
                related_name="documents",
                to="dms.tag",
            ),
        ),
    ]
