# Generated by hand per Migration Safety Policy
# Intent: Add additive search indexes on Document.content_type_id, Document.object_id, Document.status, Document.title, and Tag.name.
# Risk: Low — additive index creation only; no data rewrite or constraint changes.
# MySQL Runtime Impact: Table rebuild under lock on dms_document and dms_tag tables. Expected duration scales with row count. For large tables, run during maintenance window or use online DDL (gh-ost/pt-osc).
# Rollback: Drop indexes in a follow-up migration.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0004_tag_document_is_public_document_tags"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["content_type", "object_id"], name="dms_doc_gfk_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="dms_doc_status_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["title"], name="dms_doc_title_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name"], name="dms_tag_name_idx"),
        ),
    ]
