# Generated by Django 6.0.2 on 2026-09-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0007_document_operational_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="operational_state",
            field=models.CharField(
                choices=[
                    ("USABLE", "Usable"),
                    ("STALE", "Stale"),
                    ("UNSAFE", "Unsafe"),
                    ("SUPERSEDED", "Superseded"),
                ],
                db_index=True,
                default="USABLE",
                help_text="Whether the document is safe to use as the current operational artifact.",
                max_length=20,
            ),
        ),
    ]
