# Generated by Django 6.0.2 on 2026-09-26 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0008_alter_document_operational_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentDownloadFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_ulid", models.CharField(db_index=True, max_length=26)),
                ("document_title", models.CharField(blank=True, max_length=255)),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("document_missing", "Document not found"),
                            ("document_inactive", "Document inactive"),
                            ("document_not_current", "Document is no longer current"),
                            ("access_denied", "Access denied"),
                            ("file_missing", "File missing from storage"),
                        ],
                        max_length=40,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("trace_id", models.CharField(blank=True, max_length=255)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="download_failures",
                        to="dms.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_download_failures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Download Failure",
                "verbose_name_plural": "Document Download Failures",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["reason_code", "occurred_at"],
                        name="dms_dl_fail_reason_time_idx",
                    )
                ],
            },
        ),
    ]
