# Generated by Django 6.0.2 on 2026-09-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0009_documentdownloadfailure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentdownloadfailure",
            name="reason_code",
            field=models.CharField(
                choices=[
                    ("document_missing", "Document not found"),
                    ("document_inactive", "Document inactive"),
                    ("document_not_current", "Document is no longer current"),
                    ("document_marked_unsafe", "Document marked unsafe"),
                    (
                        "generic_generation_not_current",
                        "Generated chart is not current",
                    ),
                    ("generic_estimate_unsafe", "Generated chart estimate is unsafe"),
                    ("generic_profile_unsafe", "Generated chart profile is unsafe"),
                    ("generic_profile_changed", "Generated chart profile changed"),
                    ("generic_estimate_changed", "Generated chart estimate changed"),
                    ("estimate_unsafe", "Tank chart estimate is unsafe"),
                    ("profile_unsafe", "Tank chart profile is unsafe"),
                    (
                        "source_data_newer_than_document",
                        "Source data is newer than chart",
                    ),
                    ("tank_mapping_missing", "Tank mapping is missing"),
                    ("profile_version_changed", "Tank profile changed"),
                    ("estimate_changed", "Tank estimate changed"),
                    ("access_denied", "Access denied"),
                    ("file_missing", "File missing from storage"),
                ],
                max_length=40,
            ),
        ),
    ]
