# Generated by Django 6.0.2 on 2026-07-11 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=1024)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("submitted", "Submitted"),
                            ("resolved", "Resolved"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chart_wrong", "Chart Wrong"),
                            ("data_discrepancy", "Data Discrepancy"),
                            ("ui_glitch", "UI Glitch"),
                            ("question", "Question"),
                            ("general", "General Feedback"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("viewport_size", models.CharField(blank=True, max_length=32)),
                ("page_metadata", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["status", "timestamp"],
                        name="feedback_fe_status_a81e3b_idx",
                    ),
                    models.Index(
                        fields=["category", "timestamp"],
                        name="feedback_fe_categor_f5f8fc_idx",
                    ),
                ],
            },
        ),
    ]
