# Generated by Django 6.0.2 on 2026-07-11 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=1024)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.TextField(blank=True)),
                ("viewport_size", models.CharField(blank=True, max_length=32)),
                ("page_metadata", models.JSONField(blank=True, default=dict)),
                ("is_submitted", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_click_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="feedbackreport",
            name="click_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="feedback.feedbackclickevent",
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackclickevent",
            index=models.Index(
                fields=["timestamp"], name="feedback_fe_timesta_08a54c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackclickevent",
            index=models.Index(
                fields=["is_submitted", "timestamp"],
                name="feedback_fe_is_subm_b1ad6b_idx",
            ),
        ),
    ]
