# Generated by Django 6.0.2 on 2026-07-31 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tankcharts", "0001_create_tankchart_prereqs"),
        ("tankgauge", "0012_tankchart_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreChartGeneration",
            fields=[
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="chart_generation",
                        serialize=False,
                        to="tankgauge.store",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.IntegerField(default=0)),
                ("failure_reason", models.TextField(blank=True)),
                ("retry_after", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Store Chart Generation",
                "verbose_name_plural": "Store Chart Generations",
                "db_table": "tankcharts_storechartgeneration",
            },
        ),
    ]
