# Generated by hand per Migration Safety Policy
# Intent: Add TankChartAccessLog model for tracking tank chart downloads and email deliveries.
# Risk: Low — additive table creation only.
# MySQL Runtime Impact: Minimal — creates new table tankcharts_accesslog with 3 indexes.
# Rollback: Drop table in a follow-up migration.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0005_search_indexes"),
        ("tankgauge", "0013_search_indexes"),
        ("tankcharts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TankChartAccessLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("download", "Download"), ("email", "Email")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "chart_source",
                    models.CharField(
                        blank=True,
                        choices=[("cached", "Cached"), ("generated", "Generated")],
                        max_length=20,
                    ),
                ),
                ("generation_duration_ms", models.IntegerField(blank=True, null=True)),
                ("file_size_bytes", models.IntegerField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chart_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dms.document",
                    ),
                ),
                (
                    "sent_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tankgauge.store",
                    ),
                ),
            ],
            options={
                "db_table": "tankcharts_accesslog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "-created_at"],
                        name="tankcharts__store_i_a11fd4_idx",
                    ),
                    models.Index(
                        fields=["status"], name="tankcharts__status_6d5409_idx"
                    ),
                    models.Index(
                        fields=["delivery_method"],
                        name="tankcharts__deliver_98ef61_idx",
                    ),
                ],
            },
        ),
    ]
