# Generated by Django 6.0.2 on 2026-03-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_num", models.IntegerField(blank=True, null=True, unique=True)),
                ("riso_num", models.IntegerField(blank=True, null=True, unique=True)),
                ("store_name", models.CharField(blank=True, max_length=255, null=True)),
                ("store_type", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("county", models.CharField(blank=True, max_length=255, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("install_date", models.DateField(blank=True, null=True)),
                (
                    "overfill_protection",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("legacy_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TankType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("max_depth", models.IntegerField(blank=True, null=True)),
                ("misc_info", models.TextField(blank=True, null=True)),
                ("chart_source", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("legacy_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TankChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inches", models.IntegerField()),
                ("gallons", models.IntegerField()),
                ("tank_name", models.CharField(max_length=255)),
                ("misc_info", models.TextField(blank=True, null=True)),
                (
                    "tank_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="tankgauge.tanktype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreTankMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuel_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tank_mappings",
                        to="tankgauge.store",
                    ),
                ),
                (
                    "tank_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_mappings",
                        to="tankgauge.tanktype",
                    ),
                ),
            ],
        ),
    ]
