# Generated by Django 6.0.2 on 2026-03-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tankgauge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
