# Generated by Django 6.0.2 on 2026-03-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tankgauge", "0002_alter_store_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="tanktype",
            name="legacy_id",
        ),
    ]
