# Generated by Django 6.0.2 on 2026-04-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteintel", "0001_initial"),
        ("tankgauge", "0003_remove_store_legacy_id_remove_tanktype_legacy_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="location",
            field=models.OneToOneField(
                blank=True,
                help_text="Canonical link to Site Intelligence",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_canonical",
                to="siteintel.location",
            ),
        ),
        migrations.AddField(
            model_name="storetankmapping",
            name="tank_index",
            field=models.IntegerField(
                blank=True,
                help_text="The physical tank number (1, 2, 3...) from on-site ATG.",
                null=True,
            ),
        ),
    ]
