# Generated by Django 6.0.2 on 2026-06-14 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tankgauge", "0005_tankestimation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tankestimation",
            name="tank_mapping",
            field=models.ForeignKey(
                help_text="The physical tank being modeled.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estimations",
                to="tankgauge.storetankmapping",
            ),
        ),
    ]
