# Generated by Django 6.0.2 on 2026-06-15 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tankgauge", "0007_alter_tankestimation_tank_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualTankEstimation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        help_text="The fuel product stored.", max_length=20
                    ),
                ),
                (
                    "tank_index",
                    models.IntegerField(
                        help_text="The physical tank number (1, 2, 3...) from on-site ATG."
                    ),
                ),
                (
                    "radius",
                    models.FloatField(help_text="Estimated tank radius in inches."),
                ),
                (
                    "length",
                    models.FloatField(help_text="Estimated tank length in inches."),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Overall confidence score (0.0 to 1.0) for this estimate."
                    ),
                ),
                (
                    "mean_error",
                    models.FloatField(
                        blank=True,
                        help_text="Mean absolute error in gallons.",
                        null=True,
                    ),
                ),
                (
                    "max_error",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum observed error in gallons.",
                        null=True,
                    ),
                ),
                (
                    "sample_count",
                    models.IntegerField(
                        help_text="Number of (height, volume) points used for this estimation."
                    ),
                ),
                (
                    "estimation_method",
                    models.CharField(
                        default="HORIZONTAL_CYLINDER",
                        help_text="The mathematical model used (e.g., Horizontal Cylinder).",
                        max_length=100,
                    ),
                ),
                (
                    "algorithm_version",
                    models.CharField(
                        help_text="Version of the GeometryEngine used.", max_length=50
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="True if this is the designated 'current' estimate for this tank.",
                    ),
                ),
                (
                    "diagnostics",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed iteration data and fitting metrics.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        help_text="The physical store site.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_estimations",
                        to="tankgauge.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Tank Estimation",
                "verbose_name_plural": "Virtual Tank Estimations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "fuel_type", "tank_index"],
                        name="tankgauge_v_store_i_8ff2c6_idx",
                    )
                ],
            },
        ),
    ]
