# Generated by Django 6.0.2 on 2026-06-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tankgauge", "0008_virtualtankestimation"),
    ]

    operations = [
        migrations.AddField(
            model_name="tankchart",
            name="is_official",
            field=models.BooleanField(
                default=True,
                help_text="True if this is a manufacturer-provided chart. False if generated from telemetry.",
            ),
        ),
        migrations.AddField(
            model_name="tankchart",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_charts",
                to="tankgauge.store",
            ),
        ),
        migrations.AddField(
            model_name="tankchart",
            name="tank_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tankchart",
            name="tank_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charts",
                to="tankgauge.tanktype",
            ),
        ),
    ]
