# Generated by Django 6.0.2 on 2026-06-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tankgauge", "0010_storetankmapping_uniqueness"),
    ]

    operations = [
        migrations.CreateModel(
            name="TankGaugeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode_priority",
                    models.CharField(
                        choices=[
                            ("OFFICIAL_FIRST", "Official Tank Chart (Priority)"),
                            (
                                "MATHEMATICAL_FIRST",
                                "Mathematical / Veeder-Root (Priority)",
                            ),
                        ],
                        default="OFFICIAL_FIRST",
                        help_text="Controls which data source the calculation engine prefers when BOTH a Tank Chart AND sufficient Veeder-Root data are available for a tank. If only one source exists, that source is always used regardless of this setting.",
                        max_length=30,
                        verbose_name="Default Mode Priority",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "TankGauge Configuration",
                "verbose_name_plural": "TankGauge Configuration",
            },
        ),
    ]
