# Generated by Django 6.0.2 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tankgauge", "0011_add_tankgauge_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="tankchart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tankchart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
    ]
