# Generated by hand per Migration Safety Policy
# Intent: Add additive search indexes on Store.state and Store.city to accelerate ORM candidate lookups in Location Document Hub.
# Risk: Low — additive index creation only.
# MySQL Runtime Impact: Table rebuild under lock on Store table. Duration scales with row count. For large tables, run during maintenance window or use online DDL.
# Rollback: Drop indexes in a follow-up migration.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tankgauge", "0012_tankchart_timestamps"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["state"], name="tankgauge_s_state_98018f_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["city"], name="tankgauge_s_city_1947a1_idx"),
        ),
    ]
