# Generated by Django 6.0.2 on 2026-09-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tankgauge", "0014_correct_site_111_regular_tank"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
