# Generated by Django 6.0.2 on 2026-09-17 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tankgauge", "0015_storetype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="storetankmapping",
            name="canonical_fuel_type",
            field=models.CharField(
                blank=True,
                help_text="Normalized fuel key used for physical tank identity.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storetankmapping",
            name="capacity_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="storetankmapping",
            name="capacity_source",
            field=models.CharField(
                choices=[
                    ("MANUAL_VERIFIED", "Manual verified"),
                    ("OFFICIAL_SELECTED", "Official tank type"),
                    ("VEEDER_EXPLICIT_SELECTED", "Veeder explicit"),
                    ("VEEDER_DERIVED_SELECTED", "Veeder derived"),
                    ("LEGACY_ASSUMED", "Legacy assumed"),
                    ("UNRESOLVED", "Unresolved"),
                    ("CONFLICTING", "Conflicting"),
                ],
                default="UNRESOLVED",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="storetankmapping",
            name="capacity_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="storetankmapping",
            name="capacity_verified",
            field=models.BooleanField(
                default=False,
                help_text="True only after an administrator confirms capacity and basis.",
            ),
        ),
        migrations.AddField(
            model_name="storetankmapping",
            name="capacity_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storetankmapping",
            name="capacity_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_tank_capacity_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storetankmapping",
            name="physical_capacity_gallons",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Canonical physical 100% capacity in gallons.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storetankmapping",
            name="profile_status",
            field=models.CharField(
                choices=[
                    ("READY", "Ready"),
                    ("LEGACY_UNVERIFIED", "Legacy unverified"),
                    ("REVIEW_REQUIRED", "Review required"),
                    ("UNAVAILABLE", "Unavailable"),
                ],
                default="UNAVAILABLE",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="storetankmapping",
            name="profile_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="storetankmapping",
            name="ullage_endpoint_percent_exact",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Exact percentage represented by the printed ullage endpoint.",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tankestimation",
            name="active_slot",
            field=models.CharField(
                blank=True,
                help_text="Non-null only for the current estimate; supports MySQL uniqueness.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tankestimation",
            name="capacity_source",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="tankestimation",
            name="capacity_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tankestimation",
            name="estimate_status",
            field=models.CharField(
                choices=[
                    ("VALID", "Valid"),
                    ("LEGACY_UNVERIFIED", "Legacy unverified"),
                    ("STALE", "Stale"),
                    ("UNSAFE", "Unsafe"),
                    ("BLOCKED", "Blocked"),
                ],
                default="LEGACY_UNVERIFIED",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="tankestimation",
            name="physical_capacity_gallons",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tankestimation",
            name="profile_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="virtualtankestimation",
            name="active_slot",
            field=models.CharField(
                blank=True,
                help_text="Non-null only for the current estimate; supports MySQL uniqueness.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="virtualtankestimation",
            name="capacity_source",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="virtualtankestimation",
            name="capacity_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="virtualtankestimation",
            name="estimate_status",
            field=models.CharField(
                choices=[
                    ("VALID", "Valid"),
                    ("LEGACY_UNVERIFIED", "Legacy unverified"),
                    ("STALE", "Stale"),
                    ("UNSAFE", "Unsafe"),
                    ("BLOCKED", "Blocked"),
                ],
                default="LEGACY_UNVERIFIED",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="virtualtankestimation",
            name="physical_capacity_gallons",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="virtualtankestimation",
            name="profile_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TankCapacityProfileHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_version", models.PositiveIntegerField()),
                (
                    "previous_capacity_gallons",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "new_capacity_gallons",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("previous_verified", models.BooleanField(blank=True, null=True)),
                ("new_verified", models.BooleanField(blank=True, null=True)),
                ("previous_source", models.CharField(blank=True, max_length=40)),
                ("new_source", models.CharField(blank=True, max_length=40)),
                (
                    "previous_basis_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "new_basis_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("reason", models.TextField()),
                ("actor_type", models.CharField(default="USER", max_length=20)),
                ("source_evidence_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tank_capacity_profile_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capacity_history",
                        to="tankgauge.storetankmapping",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["mapping", "-created_at"],
                        name="tankgauge_t_mapping_2e0971_idx",
                    )
                ],
            },
        ),
    ]
