# Generated by Django 6.0.2 on 2026-09-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tankgauge", "0017_canonical_identity_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storetankmapping",
            options={
                "permissions": (
                    ("backfill_tank_capacity", "Backfill Veeder capacity evidence"),
                )
            },
        ),
        migrations.AlterField(
            model_name="storetankmapping",
            name="profile_status",
            field=models.CharField(
                choices=[
                    ("READY", "Ready"),
                    ("LEGACY_UNVERIFIED", "Legacy unverified"),
                    ("REVIEW_REQUIRED", "Review required"),
                    ("UNSAFE", "Unsafe"),
                    ("UNAVAILABLE", "Unavailable"),
                ],
                default="UNAVAILABLE",
                max_length=24,
            ),
        ),
    ]
