# Generated by Django 6.0.2 on 2026-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tankgauge", "0018_alter_storetankmapping_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tankestimation",
            constraint=models.UniqueConstraint(
                fields=("tank_mapping", "active_slot"),
                name="uniq_active_mapped_estimation_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualtankestimation",
            constraint=models.UniqueConstraint(
                fields=("store", "fuel_type", "tank_index", "active_slot"),
                name="uniq_active_virtual_estimation_slot",
            ),
        ),
    ]
