# Generated by Django 6.0.2 on 2026-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="map_preference",
            field=models.CharField(
                choices=[("STANDARD", "Standard OSM"), ("DARK", "CartoDB Dark Matter")],
                default="STANDARD",
                max_length=20,
            ),
        ),
    ]
