# Generated by Django 6.0.2 on 2026-05-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_map_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hourly_pay_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Agent hourly pay rate.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="normal_shift_end",
            field=models.TimeField(
                blank=True, help_text="Normal shift end time (e.g., 03:00).", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="normal_shift_start",
            field=models.TimeField(
                blank=True,
                help_text="Normal shift start time (e.g., 15:00).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                default="America/New_York",
                help_text="Preferred timezone for display.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Checked normal workdays (e.g., ['MON', 'TUE']).",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="callsign",
            field=models.CharField(
                blank=True, help_text="Tactical field identifier.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="driver_id",
            field=models.CharField(
                blank=True,
                help_text="Primary operator ID.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_verified_field_agent",
            field=models.BooleanField(
                default=False, help_text="Security clearance level."
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="map_preference",
            field=models.CharField(
                choices=[("STANDARD", "Standard OSM"), ("DARK", "CartoDB Dark Matter")],
                default="STANDARD",
                help_text="Preferred tactical mapping layer.",
                max_length=20,
            ),
        ),
    ]
