# Generated by Django 6.0.2 on 2026-06-12 16:06

import atg.utils.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("missionlog", "0005_global_uniqueness"),
        ("tankgauge", "0004_store_location_storetankmapping_tank_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VeederTicket",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=atg.utils.storage.generate_ulid,
                        editable=False,
                        help_text="Globally unique ULID.",
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Photographic evidence of the physical ticket.",
                        upload_to=atg.utils.storage.veeder_ticket_upload_path,
                    ),
                ),
                (
                    "ocr_text",
                    models.TextField(
                        blank=True,
                        help_text="Preserved raw OCR output for future machine learning processing.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Field observations regarding ticket condition or acquisition.",
                        null=True,
                    ),
                ),
                (
                    "ticket_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="The exact time printed on the physical ticket (Manual entry).",
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        help_text="The physical store location where the ticket was printed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veeder_tickets",
                        to="tankgauge.store",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_veeder_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Veeder Ticket",
                "verbose_name_plural": "Veeder Tickets",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="VeederReading",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=atg.utils.storage.generate_ulid,
                        editable=False,
                        help_text="Globally unique ULID.",
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tank_index",
                    models.IntegerField(
                        help_text="The physical tank ID from the ATG printout (e.g., TANK 1, 2...)."
                    ),
                ),
                ("volume", models.IntegerField(help_text="Current gallons (VOL).")),
                (
                    "ullage",
                    models.IntegerField(help_text="Remaining empty space (ULLAGE)."),
                ),
                (
                    "height",
                    models.FloatField(
                        help_text="Physical fuel depth in inches (HEIGHT)."
                    ),
                ),
                (
                    "temp",
                    models.FloatField(
                        blank=True, help_text="Product temperature (TEMP).", null=True
                    ),
                ),
                (
                    "water",
                    models.FloatField(
                        blank=True,
                        help_text="Detected water level in inches.",
                        null=True,
                    ),
                ),
                (
                    "raw_line_text",
                    models.TextField(
                        blank=True,
                        help_text="The original OCR extracted string for this specific tank line.",
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=1.0,
                        help_text="OCR confidence rating for this line (1.0 = Manual/Confirmed).",
                    ),
                ),
                (
                    "is_user_corrected",
                    models.BooleanField(
                        default=False,
                        help_text="True if a human field agent corrected or verified this entry.",
                    ),
                ),
                (
                    "fuel_type",
                    models.ForeignKey(
                        help_text="Standardized product type link.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atg_readings",
                        to="missionlog.fueltype",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="Parent ticket evidence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="atg.veederticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veeder Reading",
                "verbose_name_plural": "Veeder Readings",
                "ordering": ["ticket", "tank_index"],
            },
        ),
    ]
