# Generated by Django 6.0.2 on 2026-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veederticket",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Processing"),
                    ("PROCESSING", "Processing in Progress"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                help_text="Remote OCR workflow status.",
                max_length=20,
            ),
        ),
    ]
