# Generated by Django 6.0.2 on 2026-06-12 17:09

import atg.utils.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atg", "0002_veederticket_ocr_status"),
        ("tankgauge", "0004_store_location_storetankmapping_tank_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veederticket",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Photographic evidence of the physical ticket.",
                null=True,
                upload_to=atg.utils.storage.veeder_ticket_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="veederticket",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="The physical store location where the ticket was printed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="veeder_tickets",
                to="tankgauge.store",
            ),
        ),
    ]
