# Generated by Django 6.0.2 on 2026-06-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atg", "0003_alter_veederticket_image_alter_veederticket_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="veederticket",
            name="ocr_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when OCR processing finished. Used for latency tracking.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="veederticket",
            name="parsed_json",
            field=models.JSONField(
                blank=True,
                help_text="Snapshot of the parser's structured output. Preserved for debugging and re-processing.",
                null=True,
            ),
        ),
    ]
