# Generated by Django 6.0.2 on 2026-07-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atg", "0005_veederreadingpreflighttoken"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="veederreadingpreflighttoken",
            new_name="atg_veederr_store_i_f2b269_idx",
            old_name="atg_veederre_store_i_715305_idx",
        ),
        migrations.RenameIndex(
            model_name="veederreadingpreflighttoken",
            new_name="atg_veederr_expires_db36ee_idx",
            old_name="atg_veederre_expires_7588f6_idx",
        ),
    ]
