# Generated by Django 6.0.2 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "atg",
            "0006_rename_atg_veederre_store_i_715305_idx_atg_veederr_store_i_f2b269_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="veederreading",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
    ]
