# Generated by Django 6.0.2 on 2026-09-17 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atg", "0007_veederreading_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="veederreading",
            name="acceptance_status",
            field=models.CharField(
                choices=[
                    ("ACCEPTED", "Accepted"),
                    ("PENDING_REVIEW", "Pending review"),
                    ("REJECTED", "Rejected"),
                ],
                default="ACCEPTED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="veederreading",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="veederreading",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_veeder_readings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="veederreading",
            name="basis_status",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("SUGGESTED", "Suggested"),
                    ("CONFIRMED", "Confirmed"),
                    ("AMBIGUOUS", "Ambiguous"),
                    ("CONFLICTING", "Conflicting"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="veederreading",
            name="printed_capacity_text",
            field=models.TextField(
                blank=True,
                help_text="Original printed capacity text before normalization.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="veederreading",
            name="printed_physical_capacity_gallons",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Printed Capacity/Tank Max when identified as physical 100% capacity.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="veederreading",
            name="ullage_endpoint_gallons",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Gross plus ullage endpoint in gallons.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="veederreading",
            name="ullage_endpoint_percent_exact",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Exact endpoint percentage of printed physical capacity.",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="veederreading",
            name="height",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Physical fuel depth in inches (LEVEL/HEIGHT).",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="veederreading",
            name="ullage",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Remaining empty space in gallons (ULLAGE).",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="veederreading",
            name="volume",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Gross product volume in gallons (VOL). NET is not stored.",
                max_digits=12,
            ),
        ),
    ]
