# Generated by Django 6.0.2 on 2026-09-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genericcharts", "0004_tankestimatesyncrun_lifecycle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tankestimatesyncrun",
            options={
                "ordering": ["-created_at"],
                "permissions": (("run_tank_estimate_sync", "Run tank estimate sync"),),
            },
        ),
    ]
