# Generated by Django 6.0.2 on 2026-09-18 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genericcharts", "0005_alter_tankestimatesyncrun_options"),
        ("tankgauge", "0018_alter_storetankmapping_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tankestimatesyncrun",
            name="uniq_tank_sync_idempotency_key",
        ),
        migrations.AddConstraint(
            model_name="tankestimatesyncrun",
            constraint=models.UniqueConstraint(
                fields=("idempotency_key",), name="uniq_tank_sync_idempotency_key"
            ),
        ),
    ]
