# Generated by Django 6.0.2 on 2026-04-22 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tankgauge", "0003_remove_store_legacy_id_remove_tanktype_legacy_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Primary classification (e.g., Store, Rack, Yard)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Details regarding site characteristics",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Type",
                "verbose_name_plural": "Location Types",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Common name for the site", max_length=255
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "lat",
                    models.FloatField(
                        blank=True, help_text="High-precision Latitude", null=True
                    ),
                ),
                (
                    "lon",
                    models.FloatField(
                        blank=True, help_text="High-precision Longitude", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General field observations", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location_type",
                    models.ForeignKey(
                        help_text="Drives site-specific logic",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="siteintel.locationtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved & Applied"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "store_num",
                    models.IntegerField(
                        blank=True, help_text="Physical Store #", null=True
                    ),
                ),
                (
                    "riso_num",
                    models.IntegerField(
                        blank=True, help_text="RISO Identifier", null=True
                    ),
                ),
                ("store_name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updates",
                        to="siteintel.location",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_updates",
                        to="tankgauge.store",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TankUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tank_index",
                    models.IntegerField(
                        help_text="The physical tank number from the ATG printout (1, 2, 3...)."
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        help_text="Product type (Regular, Diesel, etc.)", max_length=50
                    ),
                ),
                (
                    "reported_capacity",
                    models.IntegerField(
                        help_text="Capacity as reported by the field agent."
                    ),
                ),
                (
                    "is_unverified",
                    models.BooleanField(
                        default=False,
                        help_text="True if no matching chart exists in the database. Requires research.",
                    ),
                ),
                (
                    "store_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tank_updates",
                        to="siteintel.storeupdate",
                    ),
                ),
                (
                    "tank_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected matching chart from database",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tankgauge.tanktype",
                    ),
                ),
            ],
        ),
    ]
