# Generated by Django 6.0.2 on 2026-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteintel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tankupdate",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("plus", "Plus"),
                    ("premium", "Premium"),
                    ("diesel", "Diesel"),
                    ("kerosene", "Kerosene"),
                ],
                help_text="Product type (Regular, Diesel, etc.)",
                max_length=20,
            ),
        ),
    ]
