# Generated by Django 6.0.2 on 2026-04-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteintel", "0002_alter_tankupdate_fuel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeupdate",
            name="location_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposed_updates",
                to="siteintel.locationtype",
            ),
        ),
    ]
