# Generated by Django 6.0.2 on 2026-04-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteintel", "0003_storeupdate_location_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeupdate",
            name="store_type",
            field=models.CharField(
                blank=True,
                help_text="Brand/Type (e.g., 7-Eleven, Speedway)",
                max_length=255,
                null=True,
            ),
        ),
    ]
