# Generated by Django 6.0.2 on 2026-04-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteintel', '0004_storeupdate_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankupdate',
            name='tank_index',
            field=models.IntegerField(blank=True, help_text='The physical tank number from the ATG printout (1, 2, 3...).', null=True),
        ),
    ]
