# Generated by Django 6.0.2 on 2026-05-02 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteintel", "0007_location_tactical_overlay_mapoverlayupdate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelRack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured Lane/Arm configuration",
                    ),
                ),
                (
                    "lockout_days",
                    models.IntegerField(
                        default=180,
                        help_text="Standard period (days) before access is locked out without check-in",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        help_text="Geospatial parent for this rack",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_rack",
                        to="siteintel.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuel Rack",
                "verbose_name_plural": "Fuel Racks",
            },
        ),
        migrations.CreateModel(
            name="RackCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="GPS accuracy in meters", null=True
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="True if captured within proximity of the rack.",
                    ),
                ),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_ins",
                        to="siteintel.fuelrack",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rack_check_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rack Check-In",
                "verbose_name_plural": "Rack Check-Ins",
                "ordering": ["-timestamp"],
            },
        ),
    ]
