# Generated by Django 6.0.2 on 2026-05-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteintel", "0008_fuelrack_rackcheckin"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAttributeDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label (e.g., 'Vapor Manifold')",
                        max_length=100,
                    ),
                ),
                (
                    "field_key",
                    models.SlugField(
                        help_text="Internal key for JSON storage (e.g., 'vapor_manifold')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("boolean", "Boolean (Yes/No)"),
                            ("number", "Number"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "sort_weight",
                    models.IntegerField(
                        default=100, help_text="Lower values appear first"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this field is mandatory in proposal forms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Attribute Definition",
                "verbose_name_plural": "Site Attribute Definitions",
                "ordering": ["sort_weight", "label"],
            },
        ),
        migrations.AddField(
            model_name="location",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured site quirks and manifold data",
            ),
        ),
        migrations.AddField(
            model_name="storeupdate",
            name="proposed_metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Proposed changes to site quirks"
            ),
        ),
    ]
