# Generated by Django 6.0.2 on 2026-05-11 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteintel", "0009_siteattributedefinition_location_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeupdate",
            name="rack_config_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Proposed Lane/Arm configuration for Fuel Rack",
            ),
        ),
        migrations.AddField(
            model_name="storeupdate",
            name="rack_lockout_days",
            field=models.IntegerField(
                blank=True, help_text="Proposed lockout period for Fuel Rack", null=True
            ),
        ),
        migrations.AddField(
            model_name="storeupdate",
            name="yard_notes",
            field=models.TextField(
                blank=True,
                help_text="Proposed yard-specific operational details",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Yard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Yard-specific operational details",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        help_text="Geospatial parent for this yard",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yard",
                        to="siteintel.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yard",
                "verbose_name_plural": "Yards",
            },
        ),
    ]
