# Generated by Django 6.0.2 on 2026-06-02 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteintel", "0010_storeupdate_rack_config_json_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HandDrawnMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fabric_json",
                    models.TextField(help_text="Fabric.js canvas data (JSON)"),
                ),
                (
                    "image_data",
                    models.TextField(help_text="Base64 encoded PNG image data"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this is the default map displayed for the location.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand_drawn_maps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand_drawn_maps",
                        to="siteintel.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hand-Drawn Map",
                "verbose_name_plural": "Hand-Drawn Maps",
            },
        ),
    ]
