# Generated by Django 6.0.2 on 2026-06-15 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteintel", "0011_handdrawnmap"),
        ("tankgauge", "0008_virtualtankestimation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="timezone",
            field=models.CharField(
                blank=True,
                help_text="Automatically determined from coordinates (e.g., 'America/New_York')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="USTVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "verification_type",
                    models.CharField(
                        choices=[("confirmed", "Confirmed"), ("updated", "Updated")],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ust_verifications",
                        to="tankgauge.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ust_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UST Verification",
                "verbose_name_plural": "UST Verification Records",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="USTPermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this is the current authoritative permit for the store.",
                    ),
                ),
                (
                    "permit_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField()),
                (
                    "permit_image",
                    models.ImageField(blank=True, null=True, upload_to="ust_permits/"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ust_permits",
                        to="tankgauge.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "UST Permit",
                "verbose_name_plural": "UST Permits",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("store",),
                        name="unique_active_permit_per_store",
                    )
                ],
            },
        ),
    ]
